"""fix table name errors

Revision ID: cd71e13771b4
Revises: 6faa7a2f8325
Create Date: 2021-05-31 11:58:57.675002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd71e13771b4'
down_revision = '6faa7a2f8325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('custumer_fullname', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=8, scale=2, decimal_return_scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
